### ISSUE TITLE
Support for CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by blakbarn** [ErikSchierboom/JsonDotNetCustomContractResolvers#13]
Is it possible to use the CamelCasePropertyNamesContractResolver with this custom contract resolver? I could not find a way to use both at the same time. I would like to say what properties I want included and then camel case them.

**Comment by ErikSchierboom** [comment]
I'm not sure if that would work. I'll look into it when I have time.

**Comment by ErikSchierboom** [comment]
@blakbarn Could you perhaps create a small repro that shows what you try to achieve?

**Comment by blakbarn** [comment]
If I use your JsonDotNetCustomContractResolvers I can't also use the CamelCasePropertyNamesContractResolver. It looks like you can only have one contract resolver. I want to limit what json is returned as well as format it before returning it to the client.

**Comment by ErikSchierboom** [comment]
This is unfortunately a limitation of JSON.NET, where you can have only one contract resolver.
