### ISSUE TITLE
Nuget package copies 97 system Framework DLLs to the output folder

### ISSUE THREAD

**Issue by alekdavis** [ErikSchierboom/JsonDotNetCustomContractResolvers#20]
If I add the `JsonDotNet.CustomContractResolvers` Nuget package to a project and do a build, I get 97 additional system framework DLLs (starting with `System.AppContecxt.dll`, `System.Collections.Current.dll`, etc. and all the way to `System.Xml.XPath.XDocument`) copied to the project output folders (`bin\Debug`, `bin\Release`). Is this really necessary? Any way to turn this off?

**Comment by ErikSchierboom** [comment]
To be honest, I don't know. If I look at the package definition, I don't see anything particularly odd: https://www.nuget.org/packages/JsonDotNet.CustomContractResolvers/ Have you tried Googling a bit?

**Comment by alekdavis** [comment]
Yes. I spent a couple of hours googling why a project would copy framework dlls in the output folders (I first thought this was something I messed up when I played with various flavors of ILMerge) but did not find anything. I then created a sample with just the Nuget packages from my original project and that's when I realized who the root offender was. :-)

**Comment by alekdavis** [comment]
And I suspect it's probably not the Nuget package. More likely some project setting.

**Comment by ErikSchierboom** [comment]
I this so too. If I open the NuGet package in the NuGet package explorer, things look okay:

![image](https://user-images.githubusercontent.com/135246/59248165-ed9fe800-8c21-11e9-8727-75272648b8ec.png)

**Comment by alekdavis** [comment]
I notice a reference to `..\..\..\..\..\..\Library\Frameworks\Mono.framework\Versions\5.16.0\lib\mono\4.6.1-api\System.ComponentModel.DataAnnotations.dll` in the project file. Could it be the culprit? I just copied the source files to my project and it built without bringing in the .NET Framework's DLLs, so this must be a project settings. Btw, I did not need to explicitly include `DataAnnotations.dll` and it works fine for a WPF app.

**Comment by ErikSchierboom** [comment]
Could be. I'll see if I can build a new version without that reference.

**Comment by ErikSchierboom** [comment]
@alekdavis I've pushed a beta release where that reference has been removed: https://www.nuget.org/packages/JsonDotNet.CustomContractResolvers/2.0.1-beta1 Could you check to see if that helps?

**Comment by alekdavis** [comment]
Will do tomorrow.

**Comment by alekdavis** [comment]
Tried the beta version and it did not help. :-(

**Comment by ErikSchierboom** [comment]
Than it must not be the package itself, sorry.

**Comment by alekdavis** [comment]
It's okay. I cloned the source files instead of using the nuget package. Works great. Thanks for the nice solution.
